version: '2'
services:
  iredadmin:
    container_name: iredadmin
    hostname: iredadmin
    domainname: hkrevolution.ddns.net
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILD_IREDADMIN: YES
        USE_IREDADMIN: YES
        HOSTNAME: hkrevolution.ddns.net
    links:
      - mysql
      - postfix
    volumes_from:
      - mysql
      - nginx

  iredapd:
    container_name: iredapd
    hostname: iredapd
    domainname: hkrevolution.ddns.net
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILD_IREDAPD: YES
        HOSTNAME: hkrevolution.ddns.net
    expose:
      - '7777'
    links:
      - mysql
      - postfix
    volumes:
      - /opt/iredapd
    volumes_from:
      - mysql
      - iredadmin

  amavisd:
    container_name: amavisd
    hostname: amavisd
    domainname: hkrevolution.ddns.net
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILD_AMAVISD: YES
        HOSTNAME: hkrevolution.ddns.net
    expose:
      - '10024'
      - '9998'
    links:
      - mysql
      - dovecot
    volumes:
      - /etc/amavis
    volumes_from:
      - mysql
      - postfix

  postfix:
    container_name: postfix
    hostname: mail
    domainname: hkrevolution.ddns.net
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILD_POSTFIX: YES
        HOSTNAME: hkrevolution.ddns.net
    ports:
      - '7025:25'
      - '7587:587'
      - '7465:465'
    links:
      - amavisd
      - ldap
    volumes:
      - /etc/postfix
      - /var/vmail
    volumes_from:
      - mysql

  dovecot:
    container_name: dovecot
    hostname: mail
    domainname: hkrevolution.ddns.net
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILD_DOVECOT: YES
        HOSTNAME: hkrevolution.ddns.net
    ports:
      - '7110:110'
      - '7995:995'
      - '7143:143'
      - '7993:993'
    expose:
      - '2000'
    links:
      - postfix
      - ldap
    volumes:
      - /etc/dovecot
    volumes_from:
      - mysql
      - postfix

  nginx:
    container_name: nginx
    hostname: mail
    domainname: hkrevolution.ddns.net
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILD_NGINX: YES
        HOSTNAME: hkrevolution.ddns.net
    ports:
      - '7080:80'
      - '7443:443'
    links:
      - mysql
    volumes:
      - /opt/www
      - /etc/uwsgi
      - /etc/nginx
    volumes_from:
      - mysql

  php:
    container_name: php
    hostname: php
    domainname: hkrevolution.ddns.net
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILD_PHP: YES
        HOSTNAME: hkrevolution.ddns.net
    links:
      - mysql
    volumes_from:
      - mysql
      - nginx

  ldap:
    container_name: ldap
    hostname: ldap
    domainname: hkrevolution.ddns.net
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILD_SSL: YES
        DOCKER_BUILD_BACKEND: YES
        HOSTNAME: hkrevolution.ddns.net
    expose:
      - '389'
      - '636'
    links:
      - mysql
    volumes:
      - /etc/ssl
      - /etc/ldap
    volumes_from:
      - mysql

  mysql:
    container_name: mysql
    hostname: mysql
    domainname: hkrevolution.ddns.net
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
    expose: 
      - '3306'
    volumes:
      - /var/lib/mysql
      - /var/log
      - /run/mysqld